group_col: "Group"
value_col: "Value"
lower_limit_col: "Lower_Limit"
upper_limit_col: "Upper_Limit"

preprocessing:
  outlier_removal:
    enabled: true
    sigma_cutoff: 3.0

analyses:
  - name: "AnovaAnalysis"
    relevance: true
    relevance_threshold: 0.25
  - name: "TTestAnalysis"
    relevance: false

plots:
  - name: "BoxPlot"

output:
  save_interactive_html: true
  save_static_html: false
  save_pdf: false
  output_directory: "outputs"
  filename_prefix: "analysis_plot"
