version: '3'

tasks:
  default:
    cmds:
      - task: run

  init:
    desc: "Initialize the virtual environment and install dependencies"
    cmds:
      - uv venv

  update:
    desc: "Update dependencies"
    cmds:
      - uv sync --upgrade

  lint:
    desc: "Lint the code with ruff"
    cmds:
      - uv run ruff .

  test:
    desc: "Run tests with pytest"
    cmds:
      - uv run pytest

  bump:patch:
    desc: "Bump the patch version of the project"
    cmds:
      - uv run bump-my-version bump patch

  bump:minor:
    desc: "Bump the minor version of the project"
    cmds:
      - uv run bump-my-version bump minor

  bump:major:
    desc: "Bump the major version of the project"
    cmds:
      - uv run bump-my-version bump major

  run:
    desc: "Run the main analysis script"
    cmds:
      - uv run python main.py

  install-chrome:
    desc: "Install Google Chrome"
    cmds:
      - uv run bash scripts/install_chrome.sh

  clean:
    desc: "Remove the contents of the output directory (cross-platform)"
    cmds:
      - uv run python scripts/clean.py
