
import pandas as pd

def add_continent_column(file_path):
    """
    Adds a 'continent' column to the CSV file based on the 'country' column.
    """
    df = pd.read_csv(file_path)

    country_to_continent = {
        "Afghanistan": "Asia",
        "Angola": "Africa",
        "Albania": "Europe",
        "Andorra": "Europe",
        "UAE": "Asia",
        "Argentina": "South America",
        "Armenia": "Asia",
        "Antigua and Barbuda": "North America",
        "Australia": "Oceania",
        "Austria": "Europe",
        "Azerbaijan": "Asia",
        "Burundi": "Africa",
        "Belgium": "Europe",
        "Benin": "Africa",
        "Burkina Faso": "Africa",
        "Bangladesh": "Asia",
        "Bulgaria": "Europe",
        "Bahrain": "Asia",
        "Bahamas": "North America",
        "Bosnia and Herzegovina": "Europe",
        "Belarus": "Europe",
        "Belize": "North America",
        "Bolivia": "South America",
        "Brazil": "South America",
        "Barbados": "North America",
        "Brunei": "Asia",
        "Bhutan": "Asia",
        "Botswana": "Africa",
        "Central African Republic": "Africa",
        "Canada": "North America",
        "Switzerland": "Europe",
        "Chile": "South America",
        "China": "Asia",
        "Cote d'Ivoire": "Africa",
        "Cameroon": "Africa",
        "Congo, Dem. Rep.": "Africa",
        "Congo, Rep.": "Africa",
        "Colombia": "South America",
        "Comoros": "Africa",
        "Cape Verde": "Africa",
        "Costa Rica": "North America",
        "Cuba": "North America",
        "Cyprus": "Europe",
        "Czech Republic": "Europe",
        "Germany": "Europe",
        "Djibouti": "Africa",
        "Dominica": "North America",
        "Denmark": "Europe",
        "Dominican Republic": "North America",
        "Algeria": "Africa",
        "Ecuador": "South America",
        "Egypt": "Africa",
        "Eritrea": "Africa",
        "Spain": "Europe",
        "Estonia": "Europe",
        "Ethiopia": "Africa",
        "Finland": "Europe",
        "Fiji": "Oceania",
        "France": "Europe",
        "Micronesia, Fed. Sts.": "Oceania",
        "Gabon": "Africa",
        "UK": "Europe",
        "Georgia": "Asia",
        "Ghana": "Africa",
        "Guinea": "Africa",
        "Gambia": "Africa",
        "Guinea-Bissau": "Africa",
        "Equatorial Guinea": "Africa",
        "Greece": "Europe",
        "Grenada": "North America",
        "Guatemala": "North America",
        "Guyana": "South America",
        "Hong Kong, China": "Asia",
        "Honduras": "North America",
        "Croatia": "Europe",
        "Haiti": "North America",
        "Hungary": "Europe",
        "Indonesia": "Asia",
        "India": "Asia",
        "Ireland": "Europe",
        "Iran": "Asia",
        "Iraq": "Asia",
        "Iceland": "Europe",
        "Israel": "Asia",
        "Italy": "Europe",
        "Jamaica": "North America",
        "Jordan": "Asia",
        "Japan": "Asia",
        "Kazakhstan": "Asia",
        "Kenya": "Africa",
        "Kyrgyz Republic": "Asia",
        "Cambodia": "Asia",
        "Kiribati": "Oceania",
        "St. Kitts and Nevis": "North America",
        "South Korea": "Asia",
        "Kuwait": "Asia",
        "Lao": "Asia",
        "Lebanon": "Asia",
        "Liberia": "Africa",
        "Libya": "Africa",
        "St. Lucia": "North America",
        "Liechtenstein": "Europe",
        "Sri Lanka": "Asia",
        "Lesotho": "Africa",
        "Lithuania": "Europe",
        "Luxembourg": "Europe",
        "Latvia": "Europe",
        "Morocco": "Africa",
        "Moldova": "Europe",
        "Madagascar": "Africa",
        "Maldives": "Asia",
        "Mexico": "North America",
        "Marshall Islands": "Oceania",
        "North Macedonia": "Europe",
        "Mali": "Africa",
        "Malta": "Europe",
        "Myanmar": "Asia",
        "Montenegro": "Europe",
        "Mongolia": "Asia",
        "Mozambique": "Africa",
        "Mauritania": "Africa",
        "Mauritius": "Africa",
        "Malawi": "Africa",
        "Malaysia": "Asia",
        "Namibia": "Africa",
        "Niger": "Africa",
        "Nigeria": "Africa",
        "Nicaragua": "North America",
        "Netherlands": "Europe",
        "Norway": "Europe",
        "Nepal": "Asia",
        "Nauru": "Oceania",
        "New Zealand": "Oceania",
        "Oman": "Asia",
        "Pakistan": "Asia",
        "Panama": "North America",
        "Peru": "South America",
        "Philippines": "Asia",
        "Palau": "Oceania",
        "Papua New Guinea": "Oceania",
        "Poland": "Europe",
        "North Korea": "Asia",
        "Portugal": "Europe",
        "Paraguay": "South America",
        "Palestine": "Asia",
        "Qatar": "Asia",
        "Romania": "Europe",
        "Russia": "Europe", # Russia is transcontinental, but often grouped with Europe for data purposes
        "Rwanda": "Africa",
        "Saudi Arabia": "Asia",
        "Sudan": "Africa",
        "Senegal": "Africa",
        "Singapore": "Asia",
        "Solomon Islands": "Oceania",
        "Sierra Leone": "Africa",
        "El Salvador": "North America",
        "Somalia": "Africa",
        "Serbia": "Europe",
        "South Sudan": "Africa",
        "Sao Tome and Principe": "Africa",
        "Suriname": "South America",
        "Slovak Republic": "Europe",
        "Slovenia": "Europe",
        "Sweden": "Europe",
        "Eswatini": "Africa",
        "Seychelles": "Africa",
        "Syria": "Asia",
        "Chad": "Africa",
        "Togo": "Africa",
        "Thailand": "Asia",
        "Tajikistan": "Asia",
        "Turkmenistan": "Asia",
        "Timor-Leste": "Asia",
        "Tonga": "Oceania",
        "Trinidad and Tobago": "North America",
        "Tunisia": "Africa",
        "Turkey": "Asia", # Turkey is transcontinental, but often grouped with Asia for data purposes
        "Tuvalu": "Oceania",
        "Taiwan": "Asia",
        "Tanzania": "Africa",
        "Uganda": "Africa",
        "Ukraine": "Europe",
        "Uruguay": "South America",
        "USA": "North America",
        "Uzbekistan": "Asia",
        "St. Vincent and the Grenadines": "North America",
        "Venezuela": "South America",
        "Vietnam": "Asia",
        "Vanuatu": "Oceania",
        "Samoa": "Oceania",
        "Yemen": "Asia",
        "South Africa": "Africa",
        "Zambia": "Africa",
        "Zimbabwe": "Africa",
    }

    df['continent'] = df['country'].map(country_to_continent)

    # Handle countries not found in the mapping
    unmapped_countries = df[df['continent'].isna()]['country'].unique()
    if len(unmapped_countries) > 0:
        print(f"Warning: The following countries were not mapped to a continent: {', '.join(unmapped_countries)}")
        df['continent'] = df['continent'].fillna('Unknown')

    return df

if __name__ == "__main__":
    # This script is intended to be run via the CLI agent,
    # but for direct testing, you can uncomment and modify the following line:
    # add_continent_column("/home/richard/programmieren/python/exan/data/co2_pcap_cons.csv")
    pass
